apiVersion: v2
name: bookstack
description: BookStack is a simple, self-hosted, easy-to-use platform for organising and storing information.
type: application
version: 2.0.0
appVersion: "25.11"
home: https://www.bookstackapp.com/
icon: https://media.githubusercontent.com/media/BookStackApp/website/master/static/images/logo.png
sources:
  - https://github.com/BookStackApp/BookStack
maintainers:
  - name: Tristan
    email: 5606292+drustan@users.noreply.github.com
dependencies:
  - name: mariadb
    version: "20.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
