apiVersion: v2
name: cryptgeon
description: A Helm chart to install cryptgeon
type: application
version: 2.9.0
appVersion: "2.8.2"
maintainers:
  - name: Drustan
    email: 5606292+drustan@users.noreply.github.com
annotations:
  artifacthub.io/category: security
  artifacthub.io/prerelease: "false"
dependencies:
- name: redis
  version: 20.x.x
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
