{{- if not .Values.app.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "app" }}
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
type: Opaque
data:
  app-key: {{ required "A random app.key is required, used as crypto salt" .Values.app.key | b64enc | quote }}
{{- end }}
