apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bookstack.fullname" . }}
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bookstack.selectorLabels" . | nindent 6 }}
{{- if .Values.deploymentStrategy }}
  strategy:
{{ toYaml .Values.deploymentStrategy | indent 4 }}
{{- end }}
  template:
    metadata:
      labels:
        {{- include "bookstack.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "bookstack.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          {{- if .Values.ldap.enabled }}
            - name: AUTH_METHOD
              value: ldap
            - name: LDAP_SERVER
              value: {{ .Values.ldap.server | quote }}
            - name: LDAP_BASE_DN
              value: {{ .Values.ldap.base_dn | quote }}
            - name: LDAP_DN
              value: {{ .Values.ldap.dn | quote }}
            - name: LDAP_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "bookstack.fullname" . }}-ldap
                  key: ldap-password
            - name: LDAP_USER_FILTER
              value: {{ .Values.ldap.userFilter | quote }}
            - name: LDAP_VERSION
              value: {{ .Values.ldap.version | quote }}
          {{- end }}
          {{- if .Values.oidc.enabled }}
            - name: OIDC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oidc.existingSecret | default (printf "%s-%s" .Release.Name "oidc") }}
                  key: oidc-client-id
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oidc.existingSecret | default (printf "%s-%s" .Release.Name "oidc") }}
                  key: oidc-client-secret
          {{- end }}
          {{- if .Values.mariadb.enabled }}
            - name: DB_HOST
              value: {{ include "bookstack.mariadb.fullname" . }}
            - name: DB_DATABASE
              value: {{ .Values.mariadb.auth.database | quote }}
            - name: DB_USERNAME
              value: {{ .Values.mariadb.auth.username | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "bookstack.mariadb.fullname" . }}
                  key: mariadb-password
          {{- else }}
            - name: DB_HOST
              value: {{ .Values.externalDatabase.host | quote }}
            - name: DB_DATABASE
              value: {{ .Values.externalDatabase.database | quote }}
            - name: DB_USERNAME
              value: {{ .Values.externalDatabase.user | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalDatabase.existingSecret | default (printf "%s-%s" .Release.Name "externaldb") }}
                  key: db-password
          {{- end }}
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.existingSecret | default (printf "%s-%s" .Release.Name "app") }}
                  key: app-key
            - name: APP_URL
              value: {{ required "value app.url is required" .Values.app.url }}
          {{- if or .Values.externalDatabase.tlsCert .Values.externalDatabase.existingTlsSecret }}
            - name: MYSQL_ATTR_SSL_CA
              value: /etc/mysql/mysql.cert
          {{- end }}
          {{- range $key, $value := .Values.env }}
            - name: {{ $key | upper | replace "." "_" }}
              value: {{ $value | quote }}
          {{- end }}
          {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: uploads
            mountPath: /var/www/bookstack/public/uploads
          - name: storage
            mountPath: /var/www/bookstack/storage/uploads
          {{- if .Values.externalDatabase.tlsCert }}
          - name: mysql-cert-file
            mountPath: /etc/mysql/
            readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: uploads
        {{- if .Values.persistence.uploads.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.uploads.existingClaim | default (printf "%s-%s" (include "bookstack.fullname" .) "uploads") }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: storage
        {{- if .Values.persistence.storage.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.storage.existingClaim | default (printf "%s-%s" (include "bookstack.fullname" .) "storage") }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: mysql-cert-file
        {{- if or .Values.externalDatabase.tlsCert .Values.externalDatabase.existingTlsSecret }}
          secret:
            secretName: {{ .Values.externalDatabase.existingTlsSecret | default (printf "%s-%s" .Release.Name "cert") }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
