{{- if and (not .Values.mariadb.enabled) (not .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externaldb" }}
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ default "" .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
