{{- if .Values.ldap.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bookstack.fullname" . }}-ldap
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
type: Opaque
stringData:
  ldap-password: {{ required "LDAP password required when LDAP is enabled" .Values.ldap.pass | quote }}
{{- end }}
