{{- if and .Values.externalDatabase.tlsCert (not .Values.externalDatabase.existingTlsSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "cert" }}
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
type: Opaque
data:
  mysql.cert: {{ .Values.externalDatabase.tlsCert | b64enc | quote }}
{{- end }}
