{{- if and .Values.oidc.enabled (not .Values.oidc.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "oidc" }}
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
type: Opaque
stringData:
  oidc-client-id: {{ required "OIDC client ID required when OIDC is enabled without existingSecret" .Values.oidc.clientId | quote }}
  oidc-client-secret: {{ required "OIDC client secret required when OIDC is enabled without existingSecret" .Values.oidc.clientSecret | quote }}
{{- end }}
