{{- if and .Values.persistence.storage.enabled (not .Values.persistence.storage.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bookstack.fullname" . }}-storage
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
  {{- with .Values.persistence.storage.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.storage.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.storage.size | quote }}
{{- if .Values.persistence.storage.storageClass }}
{{- if (eq "-" .Values.persistence.storage.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .Values.persistence.storage.storageClass | quote }}
{{- end }}
{{- end }}
{{- end }}
